#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : redshift
Version  : 1.12
Release  : 10
URL      : https://github.com/jonls/redshift/releases/download/v1.12/redshift-1.12.tar.xz
Source0  : https://github.com/jonls/redshift/releases/download/v1.12/redshift-1.12.tar.xz
Summary  : Adjusts the color temperature of your screen according to your surroundings.
Group    : Development/Tools
License  : GPL-3.0
Requires: redshift-bin = %{version}-%{release}
Requires: redshift-data = %{version}-%{release}
Requires: redshift-license = %{version}-%{release}
Requires: redshift-locales = %{version}-%{release}
Requires: redshift-man = %{version}-%{release}
Requires: redshift-python = %{version}-%{release}
Requires: redshift-python3 = %{version}-%{release}
Requires: redshift-services = %{version}-%{release}
Requires: pygobject
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-randr)
BuildRequires : pkgconfig(xxf86vm)
BuildRequires : pygobject
BuildRequires : systemd-dev

%description
Redshift
========
Redshift adjusts the color temperature of your screen according to
your surroundings. This may help your eyes hurt less if you are
working in front of the screen at night.

%package bin
Summary: bin components for the redshift package.
Group: Binaries
Requires: redshift-data = %{version}-%{release}
Requires: redshift-license = %{version}-%{release}
Requires: redshift-services = %{version}-%{release}

%description bin
bin components for the redshift package.


%package data
Summary: data components for the redshift package.
Group: Data

%description data
data components for the redshift package.


%package license
Summary: license components for the redshift package.
Group: Default

%description license
license components for the redshift package.


%package locales
Summary: locales components for the redshift package.
Group: Default

%description locales
locales components for the redshift package.


%package man
Summary: man components for the redshift package.
Group: Default

%description man
man components for the redshift package.


%package python
Summary: python components for the redshift package.
Group: Default
Requires: redshift-python3 = %{version}-%{release}

%description python
python components for the redshift package.


%package python3
Summary: python3 components for the redshift package.
Group: Default
Requires: python3-core

%description python3
python3 components for the redshift package.


%package services
Summary: services components for the redshift package.
Group: Systemd services

%description services
services components for the redshift package.


%prep
%setup -q -n redshift-1.12
cd %{_builddir}/redshift-1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583218667
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1583218667
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/redshift
cp %{_builddir}/redshift-1.12/COPYING %{buildroot}/usr/share/package-licenses/redshift/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install
%find_lang redshift

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/redshift
/usr/bin/redshift-gtk

%files data
%defattr(-,root,root,-)
/usr/share/appdata/redshift-gtk.appdata.xml
/usr/share/applications/redshift-gtk.desktop
/usr/share/applications/redshift.desktop
/usr/share/icons/hicolor/scalable/apps/redshift-status-off.svg
/usr/share/icons/hicolor/scalable/apps/redshift-status-on.svg
/usr/share/icons/hicolor/scalable/apps/redshift.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/redshift/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/redshift.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/redshift-gtk.service
/usr/lib/systemd/user/redshift.service

%files locales -f redshift.lang
%defattr(-,root,root,-)

